# Generated by Django 3.0.6 on 2020-05-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_capitale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='capitale',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='taux_actualisation',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='year_cash_flow',
            field=models.CharField(max_length=200),
        ),
    ]
